services:
  - type: web
    name: discord-bot-ngl
    env: python
    runtime: python-3.11.5
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER_ENVIRONMENT
        value: "production"
    plan: free
    region: singapore
    scaling:
      minInstances: 1
      maxInstances: 1
    autoDeploy: true
    healthCheckPath: /ping
    previewsEnabled: false